\documentclass{article}
\title {Lab 3}
\author {YOUR NAME HERE}
\usepackage{amsmath}


\begin{document}
\maketitle
\SweaveOpts{concordance=TRUE}

\section{Functions}

A function in R is a mapping from inputs (or arguments) to an output. This is very similar to the mathematical definition of a function. You have already worked with many R functions, even if you haven't thought of them in these terms (e.g. \`mean()\`, \`rnorm()\`, \`sample()\`).\\\\

What arguments do you pass into these various functions? What do they give you as output?\\\\

With the functions you have used so far, these have been defined for you by either base R or the packages that you use. However, it is possible for you to write your own functions in 'R.' This is an extremely powerful tool for tasks that need to be repeated many times.\\\\

The basic components of a function are:

-   name (should be descriptive),

-   arguments (these are your inputs), and

-   body (instructions for manipulating the inputs).\\\\

In 'R', you can make your own functions with the following syntax:

<<>>=
name <- function(arguments)
  {instructions}
@


To put things very simply: in the parentheses, you can input the 'arguments' that the function uses. In the curly brackets, you put what you want the function to 'do' with them. \\\\



Take a look at this function. Can you describe what it does? What are the components?

<<>>=
my_function <- function(x){

x - mean(x, na.rm = TRUE)
}
@



Generate some data to test your prediction
<<>>=
demean <- function(x) {  
  x - mean(x, na.rm = TRUE)
}

@



\section{Distributions}
We got intuition for marginal and conditional distributions using Andy's code. (Won't compile to PDF, so I'm omitting)\\\\


Using the "expanded" Titanic data, Show the (joint) distribution of age and survival $f(Survival, Age) = ?$\\
What's the (joint and conditional) distribution of age and survival for second class passengers? $f(Survival, Age |Class = 2) = ?$

<<>>=
data(Titanic)
titanic_df <- as.data.frame(Titanic)
expanded_titanic <- titanic_df[rep(row.names(titanic_df), titanic_df$Freq), 1:4]



#If I was trying to find the distribution of f(survival)...
#mean(expanded_titanic$Survived == 'Yes')
#1-mean(expanded_titanic$Survived == 'Yes')


#I recommend the "group_by" and "summarize" functions for conditional expectations. Here's an example of their use.
library(tidyverse)

expanded_titanic%>%
  #what groups do we want to preserve as different? everything else will be "collapsed"
  group_by(Sex)%>%
  #what summary statistics do we want to preserve? In this case I keep variance, but that's not going to be useful for you.
  summarize(var(Survived == 'Yes'))
@


\section{Variance, Covariance, Correlation}
These are all very easy in R.\\\\

Using the diamonds dataset, what's the\\
  1) variance in table?\\
  2) covariance of carat and price?\\
  3) correlation between depth and price? \\
<<>>=
#diamonds

@

Add a volume metric where volume = x*y*z.


Which metric has the highest correlation with price? Hint: the cor function can only take in numeric arguments.\\

<<>>=
#A correlation matrix might be useful here. This is an example using the iris dataframe
iris%>%
  select(-Species)%>%
  cor()
@

Visualize the matrix with corrplot()!
<<>>=
library(corrplot)
@

\end{document}
