\documentclass{article}
\title {Lab 9}
\author {YOUR NAME HERE}
\usepackage{amsmath}


\begin{document}
\maketitle
\SweaveOpts{concordance=TRUE}
\section{Categorical Predictors}

These data are from Charlotte, NC police traffic stops. Conditional on being pulled over, an officer might make an arrest, issue a citation (ticket), give a warning, or take no action. We will collapse this outcome into a binary: the last two options are "lenient" and the first two are "not lenient".


1) Which CMPD division has the lowest leniency rate? What was that rate? Same question but for stop-reason.
<<>>=
library(tidyverse)
library(estimatr)
library(resample)
library(mosaic)
library(stargazer)
library(modelsummary)
library(estimatr)
Tstops<-haven::read_dta('Charlotte Officer.dta')

@


2) Conditional on stop reason, towards what racial group are officers most often lenient? Least often?
<<>>=
lm_robust(data= Tstops,
          lenient ~ driver_race+ reason_for_stop)

unique(Tstops$driver_race)
@

3) What is the proportion of leniency for non-Hispanic White drivers, and how does that compare to Hispanic White drivers? (You can drop reason for stop)
<<>>=
lm_robust(data = Tstops,
          lenient ~ driver_race*driver_ethnicity)
@

4) What happens if we do the above, interacted with CMPD division and stop month? Can we get arbitrarily specific?
<<>>=
lm_robust(data = Tstops,
          lenient ~ driver_race*driver_ethnicity*cmpd_division)
@

5) Plot the association between a driver's age and the proportion of lenient outcomes (you'll need to group by and summarize). Is the relationship linear? If not, we probably shouldn't model the relationship as linear. 
<<>>=
Tstops%>%
  group_by(driver_age +driver_)%>%
  summarise(perc_lenient =  mean(lenient))%>%
#  mutate(date = as.Date(paste0(driver, '/01'), format = '%Y/%m/%d'))%>%
ggplot(data = .)+
  geom_line(aes(x = driver_age, y = perc_lenient))
@

6) Model the relationship between age and lenience using a more appropriate functional form.
<<>>=
@

7) There is a consensus that young, black, men are treated systematically more harshly by law enforcement. Do we have evidence for this in Charlotte traffic stops? (You may want to create a "young" category to aid with interpretation)
<<>>=

@

8) Omit the intercept of the previous for ease of interpretation.
<<>>=

@

9) Some police departments are interested in hiring Black officers. One of the reasons for doing so is that these officers would have less racial bias and treat black suspects more fairly. Do Charlotte's Black officers have more or less of a disparity in their treatment of non-Hispanic white drivers and Black drivers, compared to Charlotte's white officers?
<<>>=

@

10) What would we need to assume to use this as evidence for/against recommending that Charlotte hire more Black officers to combat prejudice in traffic stops?


\section{}
Let's assume that, if the officer cannot make an arrest, they were incorrect in believing a search was justified. Is an officer with more experience less likely to make an erroneous searc?
 
 
11) Let's say we're concerned about using OLS in binary outcome settings (this concern may be overblown...). Use a general linear model with a logistic linking function to investigate determinants of lenience (or some other question, if you can use the data)
<<>>=
library(stats)
@

12) Do the same but use a probit model. Are your results different?
<<>>=

@

\end{document}
