\documentclass{article}
\title {Lab 1}
\author {YOUR NAME HERE}

\begin{document}
\maketitle
\SweaveOpts{concordance=TRUE}

\section{Intro}
5 min
This version of an R file can do text,\\

$\frac{math}{3^{\alpha_2}}$\\


<<fig = TRUE>>=
#and Code:

library(tidyverse)

ggplot(data = mtcars)+
  geom_histogram(aes(x = mpg))

#Please rename the file to Lab_1_YourLastName.Rnw
@


\section{Set Operations}
5 min:\\
Describe in math the sets provided. Express each set two different ways.

\section{Probability}
15 min:\\
<<>>=
marble_draw<-function(n_times){
  bag<-c(rep('red',500),
         rep('blue',300),
         rep('green',1200))
  
  sample(bag, 
         n_times,
         replace = F)
}
@

Write a function to flip a coin n times, and another to roll a dice
<<>>=
coin_flip<-function(n_times){
  coin<-c('Heads','Tails')
  sample(coin,
         n_times,
         replace = T)
}

dice_roll<-function(n_times){
  die<- 1:6
  sample(die,
         n_times,
         replace =T)
}
@

Answer the following with empirically and analytically:
\begin{itemize}
  \item What is the probability I draw a red marble, flip a heads, and roll a 3?\\
  \item What is the probability I draw a blue marble, OR flip a heads, OR roll an even number?\\
\end{itemize}



\section{Conditional Probability}
10 min:\\
Given that I flipped tails, what is my probability of rolling an even number? Express it analytically and name the rules used. \\

Hint: $P(B|A) = \frac{P(A \cap B)}{P(A)}$\\

What's the probability of rain given that it's cloudy? What's the probability of it being not cloudy given that is not raining?\\
<<>>=
weather_data <- data.frame(
  Cloudy = c("Yes", "Yes", "No", "No"),
  Rain = c("Yes", "No", "Yes", "No"),
  Frequency = c(30, 15, 8, 40)
)

weather_data[weather_data$Cloudy==T & weather_data$Rainy==T]/weather_data[weather_data$Cloudy ==T]
@

\section{Total Probability and Partition}
5 min:\\
Using the law of total probability, what is the likelihood of a sunny day? \\
What conditions partition the space?


\section{Bayes}
10 min
\begin{itemize}
  \item The disease effects 2/100 people
  \item The test correctly identifies 90/100 who have the disease
  \item The test correctly identifies 85/100 who do not have the disease
\end{itemize}

If a person tests positive, what is the probability they have the disease?

<<>>=
N<-1:20

pr_M <- ((0.75^N)*0.4)/((0.75^N)*0.4 + (0.2^N)*0.6)
pr_W <- ((0.95^N)*0.4)/((0.95^N)*0.4 + (0.5^N)*0.6)
pr_W_A <- ((0.68^N)*0.5)/((0.68^N)*0.5 + (0.42^N)*0.5)
@


\end{document}
