\documentclass{article}
\title {Lab 7}
\author {YOUR NAME HERE}
\usepackage{amsmath}


\begin{document}
\maketitle
\SweaveOpts{concordance=TRUE}
\section{Power}
I engaged in bad coding practice and failed to comment my code :/ It falls you to to figure it out.


1) What does pwr.t.test do? What do the arguments d, n, sig.level, and type mean?
<<>>=
library(pwr)
library(tidyverse)

pwr.t.test(n = 300,
           d = .3,
           sig.level = 0.05,
           power = NULL,
           alternative = 'two.sided')

alpha_level<-0.05
@

2) What does this function do?
<<>>=
power.curve <- function(n){
  
  cd <- seq(0,1.5,.01)  
  samp.out <- NULL
  
  for(i in 1:length(cd)){
    power <-  pwr.t.test(d=cd[i],n=n,sig.level=alpha_level,type="two.sample")$power
    power <-  data.frame(effect.size=cd[i],power=power)
    samp.out <- rbind(samp.out,power)
  }
  
    ggplot(samp.out, aes(effect.size,power))+
    geom_line() + 
    geom_point() +
    theme_minimal() +
    #here  
    labs(title=paste0("t-test Power Curve for n=", n),
         x="Cohen's d",
         y="Power") +
    scale_x_continuous(limits = c(0,0.3))
}
@

3) What does this plot tell us? Add a line to the function that draws a line at the field's standard power level and another that has the function report out (either on the plot or in text) the required effect size.
<<>>=
power.curve(n = 5000)
@

4) What is this function doing?
<<>>=
power.curve_n <- function(cd){
  
  n <- seq(0,1000,100)
  samp.out <- NULL
  
  for(i in 1:length(n)){
    power <-  pwr.t.test(d=cd,n=n[i],sig.level=alpha_level,type="two.sample")$power
    power <-  data.frame(participants=n[i],power=power)
    samp.out <- rbind(samp.out,power)
  }
  
  
  #plot it
  ggplot(samp.out, aes(n,power))+
    geom_line() + 
    geom_point() +
    theme_minimal() +
    #here
    labs(title=paste0("t-test Power Curve for Cohen's D=", cd),
         x="N",
         y="Power")
}
@

5) What is this plot telling us? As in 3), add a line and have the function return the relevant sample.
<<>>=
power.curve_n(cd = .2)
@



\section{Randomization Inference}
Thanks to John Kainer, or whoever he got the language from.\\

In our discussion of bootstrapping, we were interested in estimating the sampling distribution of estimators. That is, the 'randomness' occurred at the level of the sample. We were interested in seeing the variability of our estimator across samples. To estimate this variability, we took 'artificial samples' from an existing sample, treating the latter as if it were the whole population. We can think of this as creating new datasets, calculating the estimate (by means of the estimator) for each, and plotting the distribution of the estimates. 

In randomization inference, randomness occurs not at the level of the sample, but rather at the level of the 'treatment', or, of one variable in which we are interested. 

Let us say we are interested in the \textbf{effect} of a job type on the prestige of an occupation. The variable 'type' is categorical and consists of: 'prof' (professional), 'wc' (white collar), and 'bc' (blue collar). Suppose we are interested only in assessing whether being a professional type job (e.g., being a doctor, lawyer, professor) effects prestige. 

Now, what we have is observational data. We know the prestige of an individual who has certain characteristics, among which is, for instance, having a 'professional' job. However, we want to know what the prestige of this same person would have been if she did not have a professional job. Yet we cannot observe this counterfactual. This is the fundamental problem of causal inference. Randomization inference is one way of getting around it. 

<<>>=
library(car)
data(Prestige)
@


We will do the following procedure.
\begin{enumerate}
  \item Specify the sharp null.
  \item Calculate the mean difference in prestige from the observational data. 
  \item Randomize mechanically the treatment (namely, having a professional job)
  \item Calculate the mean difference in prestige from the datasets where the treatment was randomized. 
  \item Compare these differences to calculate a p-value\\\\
\end{enumerate}


1) What is our null hypothesis? What is our alternative?\\



2) What is the observed difference?
<<>>=

@

3) Write code that randomly reassigns professional status to a new row, stores the new observed mean difference, as above, but using our new reassigned "treatments". Then wrap it all in a for-loop and do it 1e4 times.

<<>>=

@

4) Plot a histogram showing the differences under randomly re-shuffled treatment, with a vertical line at our observed value.

<<>>=

@

5) What proportion of resamples were as extreme or more extreme than our observed one? (Two-tailed, please!)
<<>>=

@

\end{document}
